In [89]:
pip install numpy


# getting started with numpy


In [90]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [91]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [92]:
import numpy as np
print(np.version)

<module 'numpy.version' from '/usr/local/lib/python3.6/dist-packages/numpy/version.py'>


In [93]:
import numpy as np
print(np.__version__)

1.18.5


#  create a numpy ndarray object

In [94]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [95]:
import numpy as np
arr = np.array([345])
print(arr)
print(type(arr))

[345]
<class 'numpy.ndarray'>


In [96]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [97]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [98]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(arr)
print(type(arr))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]
<class 'numpy.ndarray'>


In [99]:
import numpy as np
a = np.array(567)
b = np.array([1,2,3,4,5,6,7])
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
d = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [100]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1])

2


In [101]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[2])

3


In [102]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[3])

4


In [103]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1] + arr[2])

5


In [104]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[2] + arr[4])

8


In [105]:
import numpy as np
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd dim: ',c[1,4])

5th element on 2nd dim:  10


In [106]:
import numpy as np
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c)
print('5th element on 2nd dim: ',c[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd dim:  10


In [107]:
import numpy as np
c = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(c)
print('print the third element of second array of the first array: ',c[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]
print the third element of second array of the first array:  6


In [108]:
import numpy as np
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c)
print('last element on 2nd dim: ',c[1,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
last element on 2nd dim:  10


In [109]:
import numpy as np
c = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(c)
print('print the last element of second array of the second array: ',c[1,1,-1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]
print the last element of second array of the second array:  11


In [110]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:6])

[2 3 4 5 6]


In [111]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:5])

[2 3 4 5]


In [112]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[5:])

[ 6  7  8  9 10]


In [113]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print(c[7:])

[ 8  9 10 11 12 13 14 15 16 17 18]


In [114]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[:-1])

[1 2 3 4 5 6 7 8 9]


In [115]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[-6:-1])

[5 6 7 8 9]


In [116]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[-6:0])

[]


In [117]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[5:-3])

[6 7]


In [118]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[-3:-1])

[8 9]


In [119]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:5:2])

[2 4]


In [120]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:5:3])

[2 5]


In [121]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:6:3])

[2 5]


In [122]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:6:2])

[2 4 6]


In [123]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[::2])

[1 3 5 7 9]


In [124]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23])
print(c[::2])

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [125]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23])
print(c[2::])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [126]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23])
print(c[1::])

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [127]:
import numpy as np
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [128]:
import numpy as np
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c[0:2,1:3])

[[2 3]
 [7 8]]


In [129]:
import numpy as np
c = np.array (['Madhu','Sai','Mansi','Payal','Ashwini','Rahul'])
print(c.dtype)

<U7


In [130]:
import numpy as np
c = np.array([1,2,3,4,5])
print(c.dtype)

int64


In [131]:
import numpy as np
c = np.array([1.23,2.3,3.44,4.44,5.44])
newarray = c.astype(int)
print(newarray)
print(newarray.dtype)

[1 2 3 4 5]
int64


In [132]:
import numpy as np
c = np.array([1.23,2.34,3.44,4.44])
newarray = c.astype(int)
print(newarray)
print(newarray.dtype)

[1 2 3 4]
int64


In [133]:
import numpy as np
c = np.array([1.23,2.3,3.44,4.44,5.44])
newarray = c.astype(bool)
print(newarray)
print(newarray.dtype)

[ True  True  True  True  True]
bool


In [134]:
import numpy as np
c = np.array([1.23,2.3,3.44,4.44,5.44])
newarray = c.astype(int)
print(newarray)
print(c.dtype)

[1 2 3 4 5]
float64


In [135]:
import numpy as np
c = np.array([1.23,2.34,3.44,4.44,5.44])
newarray = c.astype(int)
print(newarray)
print(newarray.dtype)

[1 2 3 4 5]
int64


In [136]:
import numpy as np
c = np.array([1.23,2.3,3.44,4.44,5.44])
x = c.copy()
print(x)
print(c)
print(x.dtype)

[1.23 2.3  3.44 4.44 5.44]
[1.23 2.3  3.44 4.44 5.44]
float64


In [137]:
import numpy as np
c = np.array([1.23,2.3,3.44,4.44,5.44])
x = c.view()
x[0] = 34
print(x)
print(c)
print(x.dtype)

[34.    2.3   3.44  4.44  5.44]
[34.    2.3   3.44  4.44  5.44]
float64


In [138]:
import numpy as np
c = np.array([1.23,2.3,3.44,4.44,5.44])
x = c.view()
x[0]
print(x)
print(c)
print(x.dtype)

[1.23 2.3  3.44 4.44 5.44]
[1.23 2.3  3.44 4.44 5.44]
float64


In [139]:
import numpy as np
c = np.array([1.23,2.34,3.44,4.44,5.44])
x = c.view()  ## print the value of the base attribute to check if an array owns its data or not
y = c.copy()  
print(x.base)
print(y.base)


[1.23 2.34 3.44 4.44 5.44]
None


In [140]:
import numpy as np
c = np.array([1.23,2.34,3.44,4.44,5.44])
y = np.array (['Madhu','Sai','Mansi','Payal','Ashwini','Rahul'])
print(c.shape)
print(y.shape)


(5,)
(6,)


In [141]:
import numpy as np
c = np.array([1.23,2.34,3.44,4.44,5.44])
y = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c.shape)
print(y.shape)


(5,)
(2, 5)


In [142]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = c.reshape(4,3)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [143]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = c.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [144]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(arr)
print(newarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [145]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.concatenate((arr1,arr2))
print(arr1)
print(arr2)
print(newarr)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [146]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.stack((arr1,arr2),axis = 1)
print(arr1)
print(arr2)
print(newarr)

[1 2 3]
[4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [147]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.stack((arr1,arr2),axis = 0)
print(arr1)
print(arr2)
print(newarr)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [148]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.hstack((arr1,arr2))
print(arr1)
print(arr2)
print(newarr)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [149]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.vstack((arr1,arr2))
print(arr1)
print(arr2)
print(newarr)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [150]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.dstack((arr1,arr2))

print(newarr)

[[[1 4]
  [2 5]
  [3 6]]]


# split the given array in 3 parts

In [151]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [152]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [153]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,5)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [154]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,6)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [155]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,7)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64)]


In [156]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,8)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64)]


In [157]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [158]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
newarr = np.array_split(arr,4)

print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])

[1 2 3]
[4 5 6]
[7 8]
[ 9 10]


In [159]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
newarr = np.array_split(arr,5)

print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])
print(newarr[4])


[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]


In [160]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
newarr = np.array_split(arr,6)

print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])
print(newarr[4])
print(newarr[5])


[1 2]
[3 4]
[5 6]
[7 8]
[9]
[10]


In [161]:
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
newarr = np.where(arr==3)

print(newarr)


(array([2]),)


In [162]:
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
newarr = np.where(arr==4)

print(newarr)


(array([3, 5, 6]),)


In [163]:
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
newarr = np.where(arr==1)

print(newarr)


(array([0]),)


In [164]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr = np.where(arr%2 == 0)

print(newarr)


(array([1, 3, 5, 7]),)


In [165]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr = np.where(arr%2 != 0)

print(newarr)

(array([0, 2, 4, 6]),)


In [166]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr = np.where(arr%2 == 1)

print(newarr)

(array([0, 2, 4, 6]),)


In [167]:
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7)

print(x)

1


In [168]:
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7, side ='right')

print(x)

2


In [169]:
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,8, side = 'right')

print(x)

3


In [170]:
import numpy as np
arr = np.array([6,8,7,9])
x = np.searchsorted(arr,7, side = 'right')

print(x)

3


In [171]:
import numpy as np
arr = np.array([414,42,43,44])
x = arr[[True,False,True,False]]

print(x)

[414  43]


In [172]:
import numpy as np
arr = np.array([414,42,43,44])
x = arr[[True,True,True,False]]

print(x)

[414  42  43]


In [173]:
import numpy as np
arr = np.array([4,5,6,7])
x = arr[[False,False,True,True]]

print(x)

[6 7]


In [174]:
import numpy as np

arr = np.array([41,42,43,44])

filter_arr = arr>42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [175]:
import numpy as np

arr = np.array([41,42,43,44,45,46,47,48,49])

filter_arr = arr>42 

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True  True  True  True  True  True]
[43 44 45 46 47 48 49]


In [176]:
import numpy as np

arr = np.array([41,42,43,44,45,46,47,48,49,50])

filter_arr = arr>42 

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True  True  True  True  True  True  True]
[43 44 45 46 47 48 49 50]
